apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.database }}-backup-apply
spec:
  # This should never run automatically
  suspend: true
  schedule: "0 0 31 2 *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: registry-auth
          containers:
            - name: postgres-backup-apply
              image: "mayope/postgres-ssh-backup-apply:latest"
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: {{ .Values.sshSecret}}
              env:
                - name: PGHOST
                  value: "{{ .Values.databaseHost }}"
                - name: PGPORT
                  value: "5432"
                - name: PGDATABASE
                  value: {{ .Values.database }}
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.databaseSecretName }}
                      key: {{ .Values.databaseSecretKey }}
                - name: DUMP_FILE_NAME
                  value: "<<insert dump file name>>"

